### PR TITLE
fix: Change trojan serviceName to servicename

### PR DESCRIPTION
**Pull request by RManLuo**
I have changed another missing serviceName to servicename.

### CODE REVIEW

**Comment by M1Screw** [comment]
Could you also check the code format for those recently add lines?

**Comment by RManLuo** [comment]
Do you mean all the changes related to the grpc support?

**Comment by M1Screw** [comment]
Yeah, but you can also improve other parts of code if you will.

**Comment by RManLuo** [comment]
I have fixed a minor error in sni configuration. I feel like there are no more problems here. Besides, I add a udp support for clash subscription.

**Comment by M1Screw** [comment]
Good.

**Pull request merged**
