### PR TITLE
Compatible with mysql

### PR DESCRIPTION
**Pull request by ssrlive**

### CODE REVIEW

**Comment by Anankke** [comment]
LGTM, but how do we ensure that the currently installed instances have the same structure? You might need a new migration file for that. Make sure you do the both test and we can merge it in.

**Comment by ssrlive** [comment]
here my PC info:
```

$ uname -a
Linux pc 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ mysql --version
mysql  Ver 8.0.37-0ubuntu0.22.04.3 for Linux on x86_64 ((Ubuntu))

$ php -v
PHP 8.3.9 (cli) (built: Jul  5 2024 12:03:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.9, Copyright (c), by Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans

$ redis-server --version
Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6

$ nginx -v
nginx version: nginx/1.18.0 (Ubuntu)
```
Here are the installing progress  https://github.com/ssrlive/SSPanel-UIM/blob/v24.5.0/install.md

**Comment by Anankke** [comment]
I understand you. What I mean is to ensure that users who have already installed MariaDB also have the same database schema, we need a new migration file to guarantee that everyone's database structure is identical, rather than only modifying the existing original file.

**Comment by ssrlive** [comment]
Well, I'm new to PHP, and I still don't know how to write a migration file to ensure a smooth transition to the currently modified database.

Very sorry.

**Pull request closed without merging**
