### PR TITLE
Added staticUrl and downUrl to all static file retrieval

### PR DESCRIPTION
**Pull request by regendsoh**
Enable admin to store static files/client installer in /public at remote location (eg. Aliyun OSS) for better user experience.

### CODE REVIEW

**Comment by regendsoh** [comment]
Request for verification before pull into the dev. Pre-tested with no error (有可能哪里会有漏了，但我检查是没发现）

**Comment by Anankke** [comment]
惊呆了

**Comment by regendsoh** [comment]
> 惊呆了

别揍我

**Comment by regendsoh** [comment]
Cried out loud

**Comment by regendsoh** [comment]
Close as per requested by @anankke

**Pull request closed without merging**
